### ISSUE TITLE
Age input/Create account 

### ISSUE THREAD

**Issue by med4kat** [Nerds-Who-Code/Mental-Health-Tracker#29]
**Describe the bug**
Age input on Create account page takes a negative number. 

**To Reproduce**
1. Go to http://localhost:3000/register
2. Click on Age 
3. Enter -100 
4. See no given error

**Expected behavior**
See an error message that age should be positive and an integer.

**Screenshots**
<img width="370" alt="Screenshot 2022-07-17 at 22 18 31" src="https://user-images.githubusercontent.com/31211139/179425186-6778609d-cf75-46bc-9b71-b25605c731bb.png">

**Comment by med4kat** [comment]
Do we even need the age?

**Comment by steph-koopmanschap** [comment]
On which branch is this? If I am corrrect this is already fixed on the latest branch I submitted (delete-entry) branch.

I think we wanted to know the user's age to give mental health info and advice for a specific age.
My suggestion is to ask for the age once the user already registered, maybe it can be changed in the future.

**Comment by med4kat** [comment]
Got it! Sorry my bad.
