### ISSUE TITLE
Integrate notFound.css and Entry.css into TailWind

### ISSUE THREAD

**Issue by steph-koopmanschap** [Nerds-Who-Code/Mental-Health-Tracker#37]
I created notFound.css and Entry.css as quick temporary styling.

Ideally these 2 files should be deleted.
And the components (NotFound.js and Entry.js) styled with Tailwind instead.

The files are found in /client/src/components/

The styles in notFound.css and Entry.css are ugly so dont copy the styles.

**Comment by xintamosaik** [comment]
This might actually be resolved. I hope I will have time to look it up. But if anyone has tine, please test by deleting the css files and test if they make a difference.

**Comment by steph-koopmanschap** [comment]
Entry.css deleted and everything still works.
